
<div data-mage-init='{"Pulsestorm_JavascriptInitTutorial/example": {"another":"example"}}'>A single div</div>

<!-- <div id="one" class="foo">Hello World</div>
<div id="two" class="foo">
    Goodbye World
</div>    

<script type="text/x-magento-init">
    {
        "#one": {
            "Pulsestorm_JavascriptInitTutorial/example":{"config":"value"}          
        }
    }        
</script> -->


<!--<script type="text/javascript">
	requirejs(['Pulsestorm_JavascriptInitTutorial/example'],function(example){
		alert('loaded');
		console.log(example);
	});
</script>-->